//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jbNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class Land
    {
        public int ID { get; set; }
        public int IdUser { get; set; }
        public string Dr { get; set; }
        public string Zone { get; set; }
        public string District { get; set; }
        public string City { get; set; }
        public Nullable<int> WardNo { get; set; }
        public Nullable<int> LandSqm { get; set; }
        public Nullable<int> Price { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
    }
}
