//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jbNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public UserInfo()
        {
            this.Biddings = new HashSet<Bidding>();
            this.Lands = new HashSet<Land>();
        }
    
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Password { get; set; }
        public int ID { get; set; }
        public Nullable<bool> login { get; set; }
    
        public virtual ICollection<Bidding> Biddings { get; set; }
        public virtual ICollection<Land> Lands { get; set; }
    }
}
